---
- hosts: all
  tasks:
  - name: installing apache
    yum:
      name: httpd
      state: installed
    become: yes
  - name: copying the file
    copy:
      src: /home/centos/index.html
      dest: /var/www/html
    become: yes
  - name: starting apache
    service:
      name: httpd
      state: started
    become: yes
