---
- hosts: all
  tasks:
  - name: installing multiple packages
    yum:
      name:{{ item }}
      state:installed
    with_items:
      - wget
      - community.windows
    become: yes
    tags:
      - install
  - name: installing java
    yum:
      name: java
      state: latest
    become: yes
    tags:
      - java
  - name: downloading tomcat
    get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.71/bin/apache-tomcat-8.5.71-windows-x64.zip
      dest: /opt/
    become: yes
    tags:
      - download
  - name: file unzip
    unarchive:
     src: "/opt/apache-tomcat-8.5.71-windows-x64.zip"
     dest: "/opt/"
     remote_src: yes
    become: yes
    tags:
      - unarchive
  - name: renaming the apache file
    command: mv /opt/apache-tomcat-8.5.71 /opt/tomcat
    become: yes
    tags:
      - rename
  - name: starting tomcat
    shell: nohup /opt/tomcat/bin/startup.sh
    become: yes
    tags:
    - start

