---
- hosts: all
  tasks:
  - name: Installing Apache
    yum:
      name: httpd
      state: installed
    become: yes
  - name: copying the html file
    copy:
      src: "/home/centos/index.html"
      dest: "/var/www/html"
  - name: starting Apache
    service:
      name: httpd
      state: started
    become: yes

